import { MockProposal } from "@/components/proposals/types";

export const initialMockProposals: MockProposal[] = [
  {
    id: "prop-001",
    title: "Enterprise AI-Powered Analytics Platform",
    clientName: "Sarah Johnson",
    company: "TechVista Solutions",
    status: "submitted",
    winProbability: 82,
    budget: 185000,
    createdAt: "2026-07-20T10:00:00Z",
    submittedAt: "2026-07-22T14:30:00Z",
    sections: {
      coverLetter: `Dear Sarah,\n\nThank you for the opportunity to present our proposal for the Enterprise AI-Powered Analytics Platform. At MMA Business Prosperity Weapon, we understand the transformative potential of artificial intelligence in driving business intelligence.\n\nOur team has successfully delivered similar enterprise-scale analytics solutions for Fortune 500 companies, achieving an average 40% improvement in decision-making speed and 25% reduction in operational costs.\n\nWe are confident that our expertise in machine learning, data engineering, and cloud architecture positions us uniquely to deliver a solution that exceeds your expectations.\n\nBest regards,\nMMA Business Prosperity Weapon Team`,
      introduction: `MMA Business Prosperity Weapon is a leading technology consultancy specializing in AI-driven business solutions. With over 10 years of experience and a team of 50+ certified engineers, we have delivered 200+ successful projects across 30 countries.\n\nOur core competencies include:\n• Machine Learning & Deep Learning\n• Cloud-Native Architecture (AWS, Azure, GCP)\n• Real-Time Data Processing\n• Enterprise Integration\n• Security & Compliance\n\nWe bring a unique combination of technical excellence and business acumen to every engagement.`,
      technicalPlan: `Phase 1: Discovery & Architecture (4 weeks)\n- Stakeholder interviews and requirements gathering\n- System architecture design\n- Technology stack selection\n- Data source mapping\n\nPhase 2: Core Development (12 weeks)\n- Data pipeline construction\n- ML model development and training\n- Dashboard and visualization layer\n- API development and integration\n\nPhase 3: Advanced Features (8 weeks)\n- Predictive analytics engine\n- Natural language query interface\n- Automated reporting system\n- Mobile application\n\nPhase 4: Testing & Deployment (4 weeks)\n- Comprehensive QA testing\n- Performance optimization\n- Security audit\n- Production deployment and monitoring setup`,
      costEstimate: `Investment Breakdown:\n\n• Discovery & Architecture: $28,000\n• Core Development: $85,000\n• Advanced Features: $42,000\n• Testing & Deployment: $18,000\n• Project Management: $12,000\n\nTotal Investment: $185,000\n\nPayment Schedule:\n- 30% upon contract signing: $55,500\n- 30% at Phase 2 completion: $55,500\n- 25% at Phase 3 completion: $46,250\n- 15% upon final delivery: $27,750\n\nNote: This estimate includes a 10% contingency buffer.`,
      callToAction: `We are excited about the possibility of partnering with TechVista Solutions on this transformative initiative.\n\nNext Steps:\n1. Schedule a technical deep-dive session\n2. Finalize project scope and timeline\n3. Execute partnership agreement\n4. Kick off Phase 1\n\nOur team is available for a follow-up meeting at your earliest convenience. We can provide additional references, case studies, or technical demonstrations as needed.\n\nLooking forward to building something exceptional together.`,
    },
    portfolioSuggestions: ["AI Chatbot Implementation - GlobalTech", "Predictive Analytics Dashboard - FinServe Corp", "Cloud Migration & ML Pipeline - DataDrive Inc"],
  },
  {
    id: "prop-002",
    title: "Cloud Infrastructure Modernization",
    clientName: "Michael Chen",
    company: "Meridian Corp",
    status: "draft",
    winProbability: 65,
    budget: 120000,
    createdAt: "2026-07-21T09:00:00Z",
    sections: {
      coverLetter: `Dear Michael,\n\nWe propose a comprehensive cloud modernization strategy for Meridian Corp that will reduce infrastructure costs by 35% while improving scalability and reliability.\n\nOur approach leverages containerization, microservices architecture, and managed cloud services to build a future-proof infrastructure.`,
      introduction: `MMA Business Prosperity Weapon brings deep expertise in cloud-native transformations. Our certified architects have migrated over 100 enterprise workloads to modern cloud environments.`,
      technicalPlan: `Phase 1: Assessment & Planning (3 weeks)\nPhase 2: Containerization (6 weeks)\nPhase 3: Migration (8 weeks)\nPhase 4: Optimization (4 weeks)`,
      costEstimate: `Total Investment: $120,000\nBreakdown available in detailed pricing sheet.`,
      callToAction: `Ready to modernize your infrastructure? Let's schedule a technical assessment.`,
    },
    portfolioSuggestions: ["Kubernetes Migration - ScaleUp Inc", "Multi-Cloud Strategy - GlobalNet"],
  },
  {
    id: "prop-003",
    title: "E-Commerce Platform Rebuild",
    clientName: "Emma Williams",
    company: "ShopSphere",
    status: "accepted",
    winProbability: 95,
    budget: 95000,
    createdAt: "2026-07-15T11:00:00Z",
    submittedAt: "2026-07-17T10:00:00Z",
    sections: {
      coverLetter: `Dear Emma,\n\nWe are thrilled to present our proposal for rebuilding ShopSphere's e-commerce platform using cutting-edge technology that will deliver a 3x improvement in page load times and a 45% increase in conversion rates.`,
      introduction: `MMA Business Prosperity Weapon has built and optimized e-commerce platforms processing over $2B in annual transactions.`,
      technicalPlan: `Modern stack with Next.js, headless CMS, edge computing, and AI-powered personalization.`,
      costEstimate: `Total Investment: $95,000\nPhased payment over 4 milestones.`,
      callToAction: `Excited to build the future of ShopSphere's digital commerce experience.`,
    },
    portfolioSuggestions: ["Fashion E-Commerce - LuxeBrand", "B2B Marketplace - TradeConnect"],
  },
  {
    id: "prop-004",
    title: "Real-Time IoT Monitoring Dashboard",
    clientName: "David Park",
    company: "Industrial Edge",
    status: "submitted",
    winProbability: 73,
    budget: 145000,
    createdAt: "2026-07-18T08:30:00Z",
    submittedAt: "2026-07-20T16:00:00Z",
    sections: {
      coverLetter: `Dear David,\n\nIndustrial Edge's vision for real-time IoT monitoring aligns perfectly with our expertise in edge computing and real-time data visualization.`,
      introduction: `With experience in industrial IoT deployments across manufacturing, energy, and logistics sectors, we bring domain-specific knowledge to every engagement.`,
      technicalPlan: `Edge computing layer, real-time streaming pipeline, React dashboard, alerting system.`,
      costEstimate: `Total Investment: $145,000\nIncludes hardware consultation and deployment support.`,
      callToAction: `Let's revolutionize how Industrial Edge monitors and optimizes operations.`,
    },
    portfolioSuggestions: ["Smart Factory Dashboard - ManuTech", "Energy Grid Monitoring - PowerGrid Solutions"],
  },
];
